### ISSUE TITLE
issues on auth session guard v6 doc

### ISSUE THREAD

**Issue by tpoisseau** [adonisjs/v6-docs#1]
### Package version

@adonisjs/auth@9.0.1

### Describe the bug

Hello,

Today we started a new project with adonis 6, and I'm facing some errors in documentation about authentication setup.
We used the web template, so I ran `node ace configure @adonisjs/auth` as asked in https://v6-alpha.adonisjs.com/docs/auth/introduction#installation

Then follow the session guard guide https://v6-alpha.adonisjs.com/docs/auth/session_guard

- Configuration seems to be outdated because `providers` do not exists in `@adonisjs/auth`
- I tried to implement [Remember me](https://v6-alpha.adonisjs.com/docs/auth/session_guard#remember-me-feature) feature but `tokenProviders` is not exported from `@adonisjs/auth/session`. So I gave up for this feature (not mandatory) 
- I followed the [How to login](https://v6-alpha.adonisjs.com/docs/auth/session_guard#how-to-login-a-user) section and `attempt` do not exists in `auth.use('web')`. after some search in source code, I guessed the new method is 
```js
const user = await User.verifyCredentials(email, password)
await auth.use('web').login(user)
```

Best regards

**Comment by RomainLanz** [comment]
You are using the alpha documentation with the stable release. Some breaking changes have been made between those.

I have shared the link to the stable documentation in DM since it will be only public tomorrow.
