### ISSUE TITLE
Lucid documentation bad link from search engine

### ISSUE THREAD

**Issue by nicolas-lescop** [adonisjs/v6-docs#10]
### Package version

v6-docs

### Describe the bug

Hello guys, nice work on v6 !

How to reproduce:
Search on Google by example "doc Adonisjs lucid"

When I click on the page named Introduction with the url : "https://docs.adonisjs.com/guides/database/sql"
I get a "ERR_TOO_MANY_REDIRECTS"

If it is a url from old pages of the v5 documentation maybe return a 301 with the new location will be a good fix.

Thanks

**Comment by thetutlage** [comment]
Should be good now. Thanks for reporting it https://docs.adonisjs.com/guides/sql
