### ISSUE TITLE
404 errors for some link

### ISSUE THREAD

**Issue by L4znet** [adonisjs/v6-docs#105]
Hey everyone!

I've found a lot of dead link here : https://docs.adonisjs.com/guides/authentication/introduction

and that bc this links use _ instead of -
https://docs.adonisjs.com/guides/authentication/verifying_user_credentials.md
https://docs.adonisjs.com/guides/authentication/session_guard.md
https://docs.adonisjs.com/guides/authentication/access_tokens_guard.md

for example a "good" link : https://docs.adonisjs.com/guides/authentication/verifying-user-credentials

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/v6-docs/commit/f2802dd8f27eaf4b564b1a9775d095fbcfee0169
