### ISSUE TITLE
Bad link in the documentation to a Korean sports gambling site

### ISSUE THREAD

**Issue by SirMishaa** [adonisjs/v6-docs#109]
Hello, 

There is a bad link in the documentation, for NDJSON format. It links to a gambling website 😅
https://github.com/adonisjs/v6-docs/blob/b8d3e013b4a386b8bb810b789569c85291816f9f/content/docs/digging_deeper/logger.md?plain=1#L1-L7

The domain has certainly been sold or hijacked.
Maybe we should put a link to the specification instead ?

**Comment by RomainLanz** [comment]
LOL

Yes please, can you make a PR?

**Comment by SirMishaa** [comment]
> Member

Will do
