### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by arthurfaby** [adonisjs/v6-docs#114]
Hello there,

On this page : https://docs.adonisjs.com/guides/views-and-templates/inertia

Below the **Installation** title, there is a link (*Inertia starter kit*) that redirects to https://docs.adonisjs.com/guides/getting-started/installation#starter-kits.

And I think it should redirect to https://docs.adonisjs.com/guides/getting-started/installation#inertia-starter-kit.

That's all for me :)

Have a great day !

**Comment by MaximeMRF** [comment]
Hey @arthurfaby don't hesitate to open a pull request for a small fix like that, i think it's more simple :)

**Comment by RomainLanz** [comment]
Fixed.
