### ISSUE TITLE
Impossible to import additional assets

### ISSUE THREAD

**Issue by ad-momo** [adonisjs/v6-docs#117]
Hello,

For me this trick not work : 
https://github.com/adonisjs/v6-docs/blob/10560881314b070a5fac99b873973671e25af93b/content/docs/basics/vite.md?plain=1#L329

Vite detect the module is not use in JS file, so is not compile. 

In addition, if I write this below then the file generate is js file, not a svg file.
```js
const modules  = import.meta.glob(['../images/**'])
console.log(modules)
```

Thanks 😄

**Comment by RomainLanz** [comment]
Hey @ad-momo! 👋🏻  

This is more a question than an issue with the framework itself.
Since we want to keep this space clean, please use [GitHub Discussion](https://github.com/adonisjs/core/discussions) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

**Comment by ad-momo** [comment]
Ha yes sorry 😁 thank you for reply !
