### ISSUE TITLE
Documentation for `@adonisjs/cache` is missing

### ISSUE THREAD

**Issue by MickL** [adonisjs/v6-docs#122]
The [package](https://www.npmjs.com/package/@adonisjs/cache) has a 1.0.0 release and links to the [docs](https://docs.adonisjs.com/guides/cache/introduction) which just displays an empty page. 

I found this only: https://adonisjs.com/blog/future-plans-for-adonisjs-6#adonisjscache

I wonder if with this module a controller route can be cached just by adding a decorator or something like that :)

**Comment by RomainLanz** [comment]
Hey @MickL! 👋🏻 

There is no documentation because the package has not yet been released.
We plan to release it in the following weeks.
