### ISSUE TITLE
Switch databases global, how? Lucid dynamic change

### ISSUE THREAD

**Issue by brunojoao** [adonisjs/v6-docs#129]
@adonisjs/lucid/database

How to change global connection in middleware now?

Database.connection

and

Database.manager.connection not exists anymore

in docs we can change on query by query
```

import db from '@adonisjs/lucid/services/db'

/**
 * Get query client for "pg" connection
 */
const pg = db.connection('pg')

/**
 * Execute query
 */
await pg.query().select('*').from('posts')
```

But how to change global cycle life connection?

is this call?

```
      if (dbTarget) {
        Database.call(dbTarget)
      }
```

**Comment by thetutlage** [comment]
Please use the discussion forum to ask such questions.

**Comment by brunojoao** [comment]
But all Database has changed, but no documentation
