### ISSUE TITLE
Custom Exceptions error

### ISSUE THREAD

**Issue by NathaelB** [adonisjs/v6-docs#133]
In your documentation, you indicate the origin of `Exception` in `@adonisjs/core` but here this class is in `@adonisjs/core/exceptions`.

![image](https://github.com/user-attachments/assets/d3d1b403-1836-4a64-ba58-3391a9a19f8c)
<img width="687" alt="image" src="https://github.com/user-attachments/assets/9940634b-a0e3-4bc1-98a3-85bc8fc42b09">

**Comment by thetutlage** [comment]
Can you send a PR for the docs to fix it?

**Comment by NathaelB** [comment]
Yes I can

**Comment by thetutlage** [comment]
Closed by https://github.com/adonisjs/v6-docs/pull/134
