### ISSUE TITLE
Lucid make:migration command behaves differently to the documentation

### ISSUE THREAD

**Issue by IcyFoxe** [adonisjs/v6-docs#136]
Lucid documentation about migrations mentions that running `node ace make:migration users` will create `database/migrations/1630981615472_users.ts` file, however it always adds the "create" prefix and "table" suffix to the name like so:
`database/migrations/1630981615472_create_users_table.ts`.  This isn't mentioned in the documentation.

https://lucid.adonisjs.com/docs/migrations#creating-your-first-migration

I would like to know, if there is a way to adjust the `make:migration` command to my liking, for example to remove the "create" and "table" prefixed/suffixes and just pluralize the name, so it behaves like the documentation mentions.

**Comment by thetutlage** [comment]
Nope. Customizing migration filenames is not something very desired and cannot be changed. However, the documentation should be fixed in the Lucid repo. So please feel free to send a PR for that.
