### ISSUE TITLE
Partial Content support for Static file server adonisjs6 NOT WORKING

### ISSUE THREAD

**Issue by NVTuann201** [adonisjs/v6-docs#141]
Does AdonisJS 6 support partial content requests? I added the header Range: bytes=0-1 to my request, but the response still returns the full content of the file instead of the partial content. How can I get AdonisJS to handle partial content responses correctly?

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
