### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by 7nohe** [adonisjs/v6-docs#143]
Just wanted to start by saying thanks for creating such an awesome framework! AdonisJS has been a game-changer for me, and I really appreciate all the hard work that’s gone into it.

I’d love to contribute by translating the documentation into Japanese. I think it could help make AdonisJS more accessible to Japanese-speaking developers and expand the community.

If you’re cool with this idea, I’m ready to get started! Just let me know if there are any guidelines or processes I should follow.

**Comment by thetutlage** [comment]
Regarding translations. You are free to fork the repo and host the translated version yourself. We do not want to officially host it, because once we do that, it becomes our responsibility to have it available for the future releases as well.

But, we will be happy to tell the world about your translated version and link it from the official docs

**Comment by 7nohe** [comment]
Thank you for your response!

I completely understand the need to keep the official documentation manageable and consistent with future releases. I appreciate the flexibility to host the translated version on my own. I’ll proceed with forking the repo and working on the translation.

It’s great to hear that you’re open to sharing and linking the translation from the official docs. I’ll be sure to reach out once the translation is ready.

Thanks again for your support, and I’m excited to contribute in this way!

**Comment by 7nohe** [comment]
@thetutlage 
I’ve successfully completed the translation and deployed it. If there are no issues, I’d like to start sharing it with the Japanese community.

- Website: https://adonisjs-docs-ja.vercel.app
- Repository: https://github.com/7nohe/adonisjs-v6-docs-ja

**Comment by thetutlage** [comment]
That's great. I see there are some frontend errors in the console. 
![CleanShot 2024-09-02 at 11 37 27@2x](https://github.com/user-attachments/assets/5cc2dc2e-48ae-4028-b88f-d31d12657749)

**Comment by 7nohe** [comment]
@thetutlage Thank you for checking.
I have submitted a PR to fix this error. Could you please review it?
https://github.com/dimerapp/docs-theme/pull/1

**Comment by thetutlage** [comment]
Merged and released. Thanks

**Comment by 7nohe** [comment]
I have deployed the update, and there are no errors now.

**Comment by thetutlage** [comment]
Cool. That looks great. I will soon add a reference to it in the docs website :)

Thanks for your efforts.

**Comment by thetutlage** [comment]
Hey, added to the docs website. 

![CleanShot 2024-09-11 at 08 27 53@2x](https://github.com/user-attachments/assets/ddb7d7d4-dfe8-4c3d-a4b2-d9689d6057e0)
