### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by krthr** [adonisjs/v6-docs#17]
### Package version

0.0.0

### Describe the bug

I see there is a `healthCheck` field in database config but there is no mention in the docs of this.

**Comment by MaximeMRF** [comment]
Hey @krthr 

Because the heath check package is not yet migrated and it will be a separated package.
Check [this](https://v6-migration.adonisjs.com/guides/introduction#official-packages-not-yet-compatible-with-v6)

**Comment by krthr** [comment]
> Hey @krthr 
> 
> 
> 
> Because the heath check package is not yet migrated and it will be a separated package.
> 
> Check [this](https://v6-migration.adonisjs.com/guides/introduction#official-packages-not-yet-compatible-with-v6)

Oh, I see. Thanks for the response! Have a nice day
