### ISSUE TITLE
Create a dedicated template to report issue

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/v6-docs#19]
### Package version

no

### Describe the bug

Hello,

Actually, the template looks like this which make it terrible to report a documentation issue.

![image](https://github.com/adonisjs/v6-docs/assets/45267552/de45038a-991a-4fd2-a31e-ec50ffb9f62e)

**Comment by thetutlage** [comment]
Added templates to create a new issue right away without any template chooser. I think, docs issues does not need much process. 

But feel free to propose if there is another and better process for docs (while keeping it simple)
