### ISSUE TITLE
Weird phrasing in `Views and Templates`

### ISSUE THREAD

**Issue by nhedger** [adonisjs/v6-docs#22]
### Package version

n/a

### Describe the bug

The following phrasing in [Views and Templates](https://docs.adonisjs.com/guides/views-and-templates) is a bit weird.

> Optionally, you can opt for libraries like [HTMX](https://htmx.org/) or [Unpoly](https://unpoly.com/) _to progressively enhance your application navigate like an SPA._

I may PR something later, but I thought I'd report anyway, just in case I forgot.

**Comment by thetutlage** [comment]
Hey, you did not mention what's weird with that sentence? Feel free to open a PR that explains the issue in-depth and fixes it at the same time :)

**Comment by nhedger** [comment]
Hey, my bad I was a in a bit of a rush and just wanted to open the issue as not to forget about it.

There is a small grammatical error in the sentence.

```diff
- Optionally, you can opt for libraries like HTMX or Unpoly to progressively enhance your application navigate like an SPA.
+ Optionally, you can opt for libraries like HTMX or Unpoly to progressively enhance your application and navigate like an SPA.
```
