### ISSUE TITLE
Possible typo in documentation - `ref` instead of `rel`

### ISSUE THREAD

**Issue by leo-generali** [adonisjs/v6-docs#24]
### Package version
_N/A_

### Describe the bug
Congratulations on the v6 release! 

I believe I found a potential typo in the documentation. In the [Referencing assets inside Edge templates](https://github.com/adonisjs/v6-docs/blob/1af2b00aebb7076613857a6bc024a351cc2711a5/content/docs/http/assets_bundling.md?plain=1#L315C3-L315C44) section, there's an example showing how a user can link directly to a Vite compiled stylesheet. The example shows a `ref` attribute on a `<link>` tag.

I can't find any references to a `ref` attribute for the `<link>` element in the usual documentation or the HTML specifications. Is it possible that the documentation should be updated to `rel`?

If so: happy to spin up a PR and get it fixed.

#### References
- Documentation Section: [Referencing assets inside Edge templates](https://github.com/adonisjs/v6-docs/blob/1af2b00aebb7076613857a6bc024a351cc2711a5/content/docs/http/assets_bundling.md?plain=1#L315C3-L315C44)
- Relevant Code Section: [Lines 323-334](https://github.com/adonisjs/v6-docs/blob/1af2b00aebb7076613857a6bc024a351cc2711a5/content/docs/http/assets_bundling.md?plain=1#L323-L334)

### Reproduction repo
Not applicable

**Comment by Julien-R44** [comment]
indeed, definitely a typo 😁 happy to receive a PR, thanks

**Comment by leo-generali** [comment]
I'll submit PR sometime this weekend 👍
