### ISSUE TITLE
i18n Not working AdonisJS 6

### ISSUE THREAD

**Issue by brunojoao** [adonisjs/v6-docs#37]
Creating app by mode API
...
1 - npm i @adonisjs/i18n

2 - node ace configure @adonisjs/i18n

3 - file config:
import app from '@adonisjs/core/services/app'
import { defineConfig, formatters, loaders } from '@adonisjs/i18n'

const i18nConfig = defineConfig({
  defaultLocale: 'pt-br', // nothing works, fr, es... etc
  formatter: formatters.icu(),
  supportedLocales: ['pt-br'],
  loaders: [
    /**
     * The fs loader will read translations from the
     * "resources/lang" directory.
     *
     * Each subdirectory represents a locale. For example:
     *   - "resources/lang/en"
     *   - "resources/lang/fr"
     *   - "resources/lang/it"
     */
    loaders.fs({
      location: app.languageFilesPath(),
    }),
  ],
})

export default i18nConfig

----
4 - As of VineJS, no changes have been made; everything remains in English, and the 'resources' directory is not present or does not exist.

Does this only work with Edge? cant change DateTime luxor too, all returning iso in dbquery and all.

**Comment by RomainLanz** [comment]
Hey @brunojoao! 👋🏻 

Have you followed the documentation for changing Vine's messages?
📚 https://docs.adonisjs.com/guides/i18n#using-translations-with-vinejs-directly

**Comment by thetutlage** [comment]
Couple of things.

- Please format your code properly
- Ask one question in one issue
- Be more descriptive.
- Open issues in the correct repo.

Even closing these issues takes time. So be respectful of our time and then we will try our best to help you.

For now I will close this issue, and expect you to open a new one that takes care of the following pointers
