### ISSUE TITLE
response.accessDenied() does not exist but is recommended in the documentation

### ISSUE THREAD

**Issue by shankiflang** [adonisjs/v6-docs#8]
### Package version

"@adonisjs/bouncer": "^3.1.1", "@adonisjs/core": "^6.2.1"

### Describe the bug

In the https://docs.adonisjs.com/guides/authorization#performing-authorization-1 doc we can see 
```typescript
return response.accessDenied('Cannot create a post')
```
But `accessDenied()` doesn't exist on the response. Should we use `forbiden()` or should `accessDenied` normally work?

**Comment by RomainLanz** [comment]
Hey @shankiflang! 👋🏻 

This is a mistake in the documentation, you should use `response.forbiden()` or `response.unauthorized()` depending on your needs.

Could you make a PR?
